name: s4cp.docker.dev

on:
  push:
    branches:
        - dev
    paths:
      - "app/**"
      - "!**/README.md"
  workflow_dispatch:   

env:
  AWS_REGION: "us-east-1"
  SERVICE: "app"
  ENV: "dev"
  GIT_ACTOR: "@${{ github.actor }}"

jobs:
  BuildAndPushImageToECR:
    name: "Build and Push to ECR"
    runs-on: ubuntu-latest
    permissions:
      id-token: write    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_OIDC_DEV_ECR }}
          aws-region: us-west-2
          role-skip-session-tagging: true
          mask-aws-account-id: false          

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_NOTIFY_USER_LIST: ${{ env.GIT_ACTOR }}

      - name: Set short git commit SHA
        id: shortsha
        run: echo "short_sha=`echo ${GITHUB_SHA} | cut -c1-6`" >> $GITHUB_OUTPUT        

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "s4cpecr"
          IMAGE_TAG: ${{ env.SERVICE }}-${{ env.ENV }}-${{ steps.shortsha.outputs.short_sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f app/Dockerfile app
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "Docker Image : $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_STEP_SUMMARY
